import type {
  APIClient,
  Assessment,
  EvidenceSummary,
  Finding,
  MonitoringEvent,
  RatingHistoryPoint,
  RatingResult,
  RiskObject,
  ScoringCriterion,
} from '@/types'

export const riskObjects: RiskObject[] = [
  {
    id: 'ro_fxrp_vault',
    objectId: 'fxrp-vault',
    canonicalName: 'Bizantine FXRP Vault',
    objectClass: 'Pool/Vault/Market',
    publicCategory: 'Yield Vault',
    chains: ['Flare'],
    contractAddress: '0x8A21F6768C1f8075791D08546Dadf6daA0aE9b0f',
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_euler_cbxrp',
    objectId: 'euler-cbxrp-usdc',
    canonicalName: 'Euler cbXRP / USDC Market',
    objectClass: 'Pool/Vault/Market',
    publicCategory: 'Lending Market',
    chains: ['Base'],
    contractAddress: '0x1B2c9f4a2D3e5F6a7B8c9D0e1F2a3B4c5D6e7F80',
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_usdt0',
    objectId: 'usdt0',
    canonicalName: 'USDT0',
    objectClass: 'Asset',
    publicCategory: 'Stablecoin',
    chains: ['Ethereum', 'Arbitrum', 'Optimism', 'Base'],
    contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    monitoringStatus: 'Under Review',
  },
  {
    id: 'ro_flare',
    objectId: 'flare-network',
    canonicalName: 'Flare Network',
    objectClass: 'Chain',
    publicCategory: 'Layer 1',
    chains: ['Flare'],
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_aave_v3',
    objectId: 'aave-v3-core',
    canonicalName: 'Aave V3 Core Market',
    objectClass: 'Protocol',
    publicCategory: 'Lending Protocol',
    chains: ['Ethereum'],
    contractAddress: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2',
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_lido',
    objectId: 'lido-steth',
    canonicalName: 'Lido stETH',
    objectClass: 'Asset',
    publicCategory: 'Liquid Staking',
    chains: ['Ethereum'],
    contractAddress: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_stargate',
    objectId: 'stargate-bridge',
    canonicalName: 'Stargate Bridge',
    objectClass: 'Protocol',
    publicCategory: 'Cross-chain Bridge',
    chains: ['Ethereum', 'Arbitrum', 'Base', 'Polygon'],
    contractAddress: '0x8731d54E9D02c286767d56ac03e8037C07e01e98',
    monitoringStatus: 'Under Review',
  },
  {
    id: 'ro_coinbase_custody',
    objectId: 'coinbase-custody',
    canonicalName: 'Coinbase Custody',
    objectClass: 'Organization',
    publicCategory: 'Custodian',
    chains: ['Multichain'],
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_morpho_blue',
    objectId: 'morpho-blue',
    canonicalName: 'Morpho Blue',
    objectClass: 'Protocol',
    publicCategory: 'Lending Primitive',
    chains: ['Ethereum', 'Base'],
    contractAddress: '0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb',
    monitoringStatus: 'Stable',
  },
  {
    id: 'ro_ethena_usde',
    objectId: 'ethena-usde',
    canonicalName: 'Ethena USDe',
    objectClass: 'Asset',
    publicCategory: 'Synthetic Dollar',
    chains: ['Ethereum'],
    contractAddress: '0x4c9EDD5852cd905f086C759E8383e09bff1E68B3',
    monitoringStatus: 'Critical',
  },
]

export const ratings: RatingResult[] = [
  {
    id: 'rt_fxrp',
    ratingId: 'BR-2026-0041',
    objectId: 'fxrp-vault',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 76,
    publicRating: 'B-Approved',
    ratingBand: 'B',
    decision: 'Approved',
    confidence: 87,
    evidenceCoverage: 91,
    outlook: 'Stable',
    trackScores: { general: 78, asset: 74, protocolOpportunity: 77, blockchain: 80 },
    activeGates: ['Custody attestation verified', 'Withdrawal buffer maintained'],
    activeCaps: ['Max protocol exposure 35% NAV', 'Max chain exposure 50% NAV'],
    publishedAt: '2026-08-05',
    dataCutoffAt: '2026-08-05T13:00:00Z',
  },
  {
    id: 'rt_euler',
    ratingId: 'BR-2026-0038',
    objectId: 'euler-cbxrp-usdc',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 72,
    publicRating: 'B-Constrained',
    ratingBand: 'B',
    decision: 'Approved with Constraints',
    confidence: 82,
    evidenceCoverage: 85,
    outlook: 'Stable',
    trackScores: { general: 73, asset: 70, protocolOpportunity: 74, blockchain: 71 },
    activeGates: ['Oracle redundancy required'],
    activeCaps: ['Max supply cap enforced', 'LTV ceiling 72%'],
    publishedAt: '2026-08-02',
    dataCutoffAt: '2026-08-02T09:00:00Z',
  },
  {
    id: 'rt_usdt0',
    ratingId: 'BR-2026-0033',
    objectId: 'usdt0',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 68,
    publicRating: 'C-Constrained',
    ratingBand: 'C',
    decision: 'Approved with Constraints',
    confidence: 74,
    evidenceCoverage: 79,
    outlook: 'Under Review',
    trackScores: { general: 69, asset: 66, protocolOpportunity: 68, blockchain: 70 },
    activeGates: ['Reserve attestation cadence', 'Bridge dependency disclosure'],
    activeCaps: ['Max holding 20% NAV'],
    publishedAt: '2026-07-30',
    dataCutoffAt: '2026-07-30T12:00:00Z',
  },
  {
    id: 'rt_flare',
    ratingId: 'BR-2026-0029',
    objectId: 'flare-network',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 74,
    publicRating: 'B-Constrained',
    ratingBand: 'B',
    decision: 'Approved with Constraints',
    confidence: 80,
    evidenceCoverage: 83,
    outlook: 'Stable',
    trackScores: { general: 75, asset: 72, protocolOpportunity: 73, blockchain: 78 },
    activeGates: ['Validator decentralization threshold'],
    activeCaps: ['Max chain exposure 50% NAV'],
    publishedAt: '2026-07-28',
    dataCutoffAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'rt_aave',
    ratingId: 'BR-2026-0021',
    objectId: 'aave-v3-core',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 84,
    publicRating: 'A-Approved',
    ratingBand: 'A',
    decision: 'Approved',
    confidence: 92,
    evidenceCoverage: 95,
    outlook: 'Positive',
    trackScores: { general: 86, asset: 82, protocolOpportunity: 85, blockchain: 84 },
    activeGates: [],
    activeCaps: ['Isolation mode caps enforced'],
    publishedAt: '2026-07-20',
    dataCutoffAt: '2026-07-20T14:00:00Z',
  },
  {
    id: 'rt_lido',
    ratingId: 'BR-2026-0018',
    objectId: 'lido-steth',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 81,
    publicRating: 'A-Constrained',
    ratingBand: 'A',
    decision: 'Approved with Constraints',
    confidence: 89,
    evidenceCoverage: 90,
    outlook: 'Stable',
    trackScores: { general: 83, asset: 80, protocolOpportunity: 79, blockchain: 82 },
    activeGates: ['Withdrawal queue depth monitoring'],
    activeCaps: ['Max holding 30% NAV'],
    publishedAt: '2026-07-15',
    dataCutoffAt: '2026-07-15T11:00:00Z',
  },
  {
    id: 'rt_stargate',
    ratingId: 'BR-2026-0012',
    objectId: 'stargate-bridge',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 63,
    publicRating: 'C-Constrained',
    ratingBand: 'C',
    decision: 'Approved with Constraints',
    confidence: 71,
    evidenceCoverage: 76,
    outlook: 'Negative',
    trackScores: { general: 64, asset: 61, protocolOpportunity: 62, blockchain: 66 },
    activeGates: ['Guardian multisig disclosure'],
    activeCaps: ['Max single-transfer notional'],
    publishedAt: '2026-07-10',
    dataCutoffAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'rt_coinbase',
    ratingId: 'BR-2026-0007',
    objectId: 'coinbase-custody',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 88,
    publicRating: 'A-Approved',
    ratingBand: 'A',
    decision: 'Approved',
    confidence: 94,
    evidenceCoverage: 96,
    outlook: 'Stable',
    trackScores: { general: 90, asset: 86, protocolOpportunity: 87, blockchain: 88 },
    activeGates: [],
    activeCaps: [],
    publishedAt: '2026-07-05',
    dataCutoffAt: '2026-07-05T15:00:00Z',
  },
  {
    id: 'rt_morpho',
    ratingId: 'BR-2026-0025',
    objectId: 'morpho-blue',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 79,
    publicRating: 'B-Approved',
    ratingBand: 'B',
    decision: 'Approved',
    confidence: 85,
    evidenceCoverage: 88,
    outlook: 'Positive',
    trackScores: { general: 80, asset: 77, protocolOpportunity: 81, blockchain: 78 },
    activeGates: [],
    activeCaps: ['Per-market supply caps'],
    publishedAt: '2026-07-24',
    dataCutoffAt: '2026-07-24T13:00:00Z',
  },
  {
    id: 'rt_ethena',
    ratingId: 'BR-2026-0031',
    objectId: 'ethena-usde',
    methodologyVersion: 'BL-APB v0.2',
    publicScore: 52,
    publicRating: 'D-Constrained',
    ratingBand: 'D',
    decision: 'Approved with Constraints',
    confidence: 63,
    evidenceCoverage: 70,
    outlook: 'Negative',
    trackScores: { general: 54, asset: 48, protocolOpportunity: 53, blockchain: 55 },
    activeGates: ['Funding-rate stress disclosure', 'Custodial concentration review'],
    activeCaps: ['Max holding 10% NAV'],
    publishedAt: '2026-07-31',
    dataCutoffAt: '2026-07-31T16:00:00Z',
  },
]

export const ratingHistory: Record<string, RatingHistoryPoint[]> = {
  'fxrp-vault': [
    { date: '2026-02', score: 68, rating: 'C-Constrained' },
    { date: '2026-03', score: 70, rating: 'B-Constrained' },
    { date: '2026-04', score: 71, rating: 'B-Constrained', event: 'Monitoring integration verified' },
    { date: '2026-05', score: 73, rating: 'B-Constrained' },
    { date: '2026-06', score: 74, rating: 'B-Constrained' },
    { date: '2026-07', score: 75, rating: 'B-Approved', event: 'Decision upgraded to Approved' },
    { date: '2026-08', score: 76, rating: 'B-Approved' },
  ],
}

export const findings: Finding[] = [
  {
    id: 'f_1',
    objectId: 'fxrp-vault',
    severity: 'Medium',
    title: 'Cross-chain settlement introduces bridge finality dependency',
    status: 'Open',
    detectedAt: '2026-06-18',
    updatedAt: '2026-08-01',
  },
  {
    id: 'f_2',
    objectId: 'fxrp-vault',
    severity: 'Low',
    title: 'Oracle heartbeat threshold not documented in public spec',
    status: 'Mitigated',
    detectedAt: '2026-05-30',
    updatedAt: '2026-07-22',
  },
  {
    id: 'f_3',
    objectId: 'fxrp-vault',
    severity: 'High',
    title: 'Upgradeable proxy admin key held by 3-of-5 multisig without timelock',
    status: 'Open',
    detectedAt: '2026-07-02',
    updatedAt: '2026-08-04',
  },
  {
    id: 'f_4',
    objectId: 'fxrp-vault',
    severity: 'Informational',
    title: 'Limited historical operating period under stress conditions',
    status: 'Accepted',
    detectedAt: '2026-04-11',
    updatedAt: '2026-06-15',
  },
  {
    id: 'f_5',
    objectId: 'fxrp-vault',
    severity: 'Medium',
    title: 'Liquidity concentration in a single deployment pool exceeds soft target',
    status: 'Open',
    detectedAt: '2026-07-28',
    updatedAt: '2026-08-05',
  },
]

export const evidenceSummary: Record<string, EvidenceSummary[]> = {
  'fxrp-vault': [
    { category: 'Onchain', count: 28 },
    { category: 'Documentation', count: 17, licensed: true },
    { category: 'Audit', count: 6, licensed: true },
    { category: 'Monitoring', count: 12 },
    { category: 'Legal / organizational', count: 4, licensed: true },
  ],
}

export const monitoringEvents: MonitoringEvent[] = [
  {
    id: 'me_1',
    objectId: 'ethena-usde',
    objectName: 'Ethena USDe',
    type: 'Liquidity decline',
    severity: 'Critical',
    chain: 'Ethereum',
    description: 'Backing collateral funding rate turned sharply negative; redemption depth thinned 34% in 24h.',
    detectedAt: '2026-08-05T09:12:00Z',
  },
  {
    id: 'me_2',
    objectId: 'stargate-bridge',
    objectName: 'Stargate Bridge',
    type: 'Admin-role change',
    severity: 'High',
    chain: 'Arbitrum',
    description: 'Guardian multisig signer set rotated; new signer not yet attested in disclosure registry.',
    detectedAt: '2026-08-04T18:40:00Z',
  },
  {
    id: 'me_3',
    objectId: 'usdt0',
    objectName: 'USDT0',
    type: 'Rating under review',
    severity: 'Medium',
    chain: 'Multichain',
    description: 'Reserve attestation cadence lapsed beyond methodology threshold; rating placed under review.',
    detectedAt: '2026-08-03T11:05:00Z',
  },
  {
    id: 'me_4',
    objectId: 'aave-v3-core',
    objectName: 'Aave V3 Core Market',
    type: 'Oracle configuration change',
    severity: 'Low',
    chain: 'Ethereum',
    description: 'Chainlink price feed heartbeat parameters updated within governance-approved bounds.',
    detectedAt: '2026-08-02T14:22:00Z',
  },
  {
    id: 'me_5',
    objectId: 'morpho-blue',
    objectName: 'Morpho Blue',
    type: 'Contract upgrade',
    severity: 'Info',
    chain: 'Base',
    description: 'Peripheral bundler contract deployed; core singleton unchanged and immutable.',
    detectedAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'me_6',
    objectId: 'fxrp-vault',
    objectName: 'Bizantine FXRP Vault',
    type: 'Withdrawal disruption',
    severity: 'Medium',
    chain: 'Flare',
    description: 'Withdrawal buffer briefly dipped below target during large redemption; restored within 40 minutes.',
    detectedAt: '2026-07-30T21:15:00Z',
  },
  {
    id: 'me_7',
    objectId: 'lido-steth',
    objectName: 'Lido stETH',
    type: 'Rating superseded',
    severity: 'Info',
    chain: 'Ethereum',
    description: 'Prior rating BR-2026-0009 superseded by BR-2026-0018 following methodology refresh.',
    detectedAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'me_8',
    objectId: 'ethena-usde',
    objectName: 'Ethena USDe',
    type: 'Exploit or incident',
    severity: 'High',
    chain: 'Ethereum',
    description: 'Third-party integration reported partial outage; no loss of backing assets confirmed.',
    detectedAt: '2026-07-12T03:30:00Z',
  },
]

export const assessments: Assessment[] = [
  {
    id: 'as_1',
    assessmentId: 'ASMT-2026-118',
    objectId: 'ethena-usde',
    objectName: 'Ethena USDe',
    objectClass: 'Asset',
    methodologyVersion: 'BL-APB v0.2',
    status: 'In Review',
    leadAnalyst: 'M. Halvorsen',
    completion: 88,
    evidenceCoverage: 70,
    confidence: 63,
    deadline: '2026-08-09',
    lastModified: '2026-08-05',
  },
  {
    id: 'as_2',
    assessmentId: 'ASMT-2026-121',
    objectId: 'fxrp-vault',
    objectName: 'Bizantine FXRP Vault',
    objectClass: 'Pool/Vault/Market',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Published',
    leadAnalyst: 'R. Okonkwo',
    completion: 100,
    evidenceCoverage: 91,
    confidence: 87,
    lastModified: '2026-08-05',
  },
  {
    id: 'as_3',
    assessmentId: 'ASMT-2026-124',
    objectId: 'stargate-bridge',
    objectName: 'Stargate Bridge',
    objectClass: 'Protocol',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Draft',
    leadAnalyst: 'A. Ferreira',
    completion: 42,
    evidenceCoverage: 58,
    confidence: 55,
    deadline: '2026-08-14',
    lastModified: '2026-08-04',
  },
  {
    id: 'as_4',
    assessmentId: 'ASMT-2026-125',
    objectId: 'morpho-blue',
    objectName: 'Morpho Blue',
    objectClass: 'Protocol',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Approved',
    leadAnalyst: 'R. Okonkwo',
    completion: 100,
    evidenceCoverage: 88,
    confidence: 85,
    deadline: '2026-08-07',
    lastModified: '2026-08-03',
  },
  {
    id: 'as_5',
    assessmentId: 'ASMT-2026-127',
    objectId: 'usdt0',
    objectName: 'USDT0',
    objectClass: 'Asset',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Returned',
    leadAnalyst: 'L. Nakamura',
    completion: 76,
    evidenceCoverage: 79,
    confidence: 74,
    deadline: '2026-08-11',
    lastModified: '2026-08-02',
  },
  {
    id: 'as_6',
    assessmentId: 'ASMT-2026-129',
    objectId: 'flare-network',
    objectName: 'Flare Network',
    objectClass: 'Chain',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Draft',
    leadAnalyst: 'A. Ferreira',
    completion: 31,
    evidenceCoverage: 44,
    confidence: 48,
    deadline: '2026-08-20',
    lastModified: '2026-08-01',
  },
  {
    id: 'as_7',
    assessmentId: 'ASMT-2026-131',
    objectId: 'lido-steth',
    objectName: 'Lido stETH',
    objectClass: 'Asset',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Draft',
    leadAnalyst: 'M. Halvorsen',
    completion: 55,
    evidenceCoverage: 68,
    confidence: 61,
    deadline: '2026-08-18',
    lastModified: '2026-07-31',
  },
  {
    id: 'as_8',
    assessmentId: 'ASMT-2026-133',
    objectId: 'aave-v3-core',
    objectName: 'Aave V3 Core Market',
    objectClass: 'Protocol',
    methodologyVersion: 'BL-APB v0.2',
    status: 'Rejected',
    leadAnalyst: 'L. Nakamura',
    completion: 100,
    evidenceCoverage: 62,
    confidence: 58,
    lastModified: '2026-07-26',
  },
]

export const scoringCriteria: ScoringCriterion[] = [
  {
    id: 'cr_1',
    track: 'General',
    title: 'Governance & upgrade controls',
    mechanism:
      'Evaluates admin key custody, timelock enforcement, and the process by which privileged contract changes are authorized and disclosed.',
    weight: 0.18,
    applicable: true,
    normalizedScore: 72,
    blApbScore: 74,
    confidence: 84,
    linkedEvidence: 9,
    rationale:
      'Upgrade authority is held by a 3-of-5 multisig. A timelock is configured but the guardian bypass path is not fully documented publicly.',
    manualOverride: false,
    qualityFlags: [],
    guidance:
      'Score reflects both the technical control (timelock, multisig threshold) and the transparency of the change-management process.',
    methodologyExcerpt:
      'BL-APB §3.2 — Governance controls are scored on custody model, revocation capability, and disclosure completeness.',
  },
  {
    id: 'cr_2',
    track: 'Asset',
    title: 'Collateral quality & concentration',
    mechanism:
      'Assesses the quality, liquidity, and concentration of underlying assets backing the vault deployment.',
    weight: 0.15,
    applicable: true,
    normalizedScore: 68,
    blApbScore: 70,
    confidence: 79,
    linkedEvidence: 7,
    rationale:
      'Deployments are diversified across three venues, though a single pool briefly exceeded the 15% concentration soft target.',
    manualOverride: true,
    overrideJustification:
      'Manual downward adjustment applied due to concentration breach observed in the July monitoring window.',
    qualityFlags: ['Concentration breach observed'],
    guidance: 'Concentration above soft targets should be reflected as a downward adjustment even where quality is high.',
    methodologyExcerpt:
      'BL-APB §4.1 — Asset track weighs quality and concentration; breaches of soft caps require documented rationale.',
  },
  {
    id: 'cr_3',
    track: 'Protocol',
    title: 'Operational monitoring & incident response',
    mechanism:
      'Reviews the presence and rigor of continuous monitoring, alerting thresholds, and documented incident response procedures.',
    weight: 0.14,
    applicable: true,
    normalizedScore: 81,
    blApbScore: 80,
    confidence: 90,
    linkedEvidence: 12,
    rationale:
      'Continuous monitoring is verified with defined thresholds and a documented escalation runbook validated in the July withdrawal event.',
    manualOverride: false,
    qualityFlags: [],
    guidance: 'Full marks require evidence of monitoring in production, not just documented intent.',
    methodologyExcerpt:
      'BL-APB §5.3 — Operational controls require demonstrable monitoring coverage and tested response procedures.',
  },
  {
    id: 'cr_4',
    track: 'Blockchain',
    title: 'Settlement layer & finality assurances',
    mechanism:
      'Evaluates the security, decentralization, and finality guarantees of the underlying settlement chain.',
    weight: 0.12,
    applicable: true,
    normalizedScore: 80,
    blApbScore: 80,
    confidence: 82,
    linkedEvidence: 5,
    rationale:
      'Flare provides deterministic finality with an acceptable validator distribution; cross-chain dependency remains a residual factor.',
    manualOverride: false,
    qualityFlags: ['Stale evidence'],
    guidance: 'Chain-level scores should account for validator concentration and reorg history.',
    methodologyExcerpt:
      'BL-APB §6.1 — Blockchain track assesses consensus security, finality, and validator decentralization.',
  },
]

export const apiClients: APIClient[] = [
  {
    id: 'cl_1',
    organization: 'Meridian Digital Asset Management',
    plan: 'Enterprise',
    status: 'Active',
    scopes: ['ratings:read', 'history:read', 'monitoring:read', 'webhooks', 'exports'],
    monthlyUsage: 1284920,
    rateLimit: '600 req/min',
    redistributionRights: true,
    renewalDate: '2027-01-31',
  },
  {
    id: 'cl_2',
    organization: 'Harbor Vault Curators',
    plan: 'Professional',
    status: 'Active',
    scopes: ['ratings:read', 'history:read', 'monitoring:read', 'webhooks'],
    monthlyUsage: 342110,
    rateLimit: '240 req/min',
    redistributionRights: false,
    renewalDate: '2026-11-15',
  },
  {
    id: 'cl_3',
    organization: 'Northwind Risk Committee',
    plan: 'Professional',
    status: 'Past Due',
    scopes: ['ratings:read', 'history:read', 'monitoring:read'],
    monthlyUsage: 198740,
    rateLimit: '240 req/min',
    redistributionRights: false,
    renewalDate: '2026-08-31',
  },
  {
    id: 'cl_4',
    organization: 'Sable Protocol Labs',
    plan: 'Developer',
    status: 'Trialing',
    scopes: ['ratings:read'],
    monthlyUsage: 41220,
    rateLimit: '60 req/min',
    redistributionRights: false,
    renewalDate: '2026-08-22',
  },
  {
    id: 'cl_5',
    organization: 'Public Registry Consumer',
    plan: 'Public',
    status: 'Active',
    scopes: ['ratings:read'],
    monthlyUsage: 9840,
    rateLimit: '20 req/min',
    redistributionRights: false,
    renewalDate: '—',
  },
  {
    id: 'cl_6',
    organization: 'Aegis Security Group',
    plan: 'Enterprise',
    status: 'Suspended',
    scopes: ['ratings:read', 'monitoring:read', 'webhooks'],
    monthlyUsage: 0,
    rateLimit: '600 req/min',
    redistributionRights: true,
    renewalDate: '2026-12-01',
  },
]

// Homepage aggregate metrics
export const marketOverview = {
  ratedObjects: 48,
  activeRatings: 41,
  underReview: 4,
  monitoredNetworks: 12,
}

export const ratingDistribution: { band: string; count: number }[] = [
  { band: 'A', count: 6 },
  { band: 'B', count: 18 },
  { band: 'C', count: 13 },
  { band: 'D', count: 4 },
  { band: 'Not Approved', count: 7 },
]

export const recentActions: { id: string; action: string; object: string; at: string }[] = [
  { id: 'ra_1', action: 'New rating published', object: 'Bizantine FXRP Vault', at: '2026-08-05' },
  { id: 'ra_2', action: 'Rating placed under review', object: 'USDT0', at: '2026-08-03' },
  { id: 'ra_3', action: 'Rating superseded', object: 'Lido stETH', at: '2026-07-15' },
  { id: 'ra_4', action: 'Monitoring event detected', object: 'Ethena USDe', at: '2026-08-05' },
]

// Dashboard aggregate metrics
export const dashboardMetrics = {
  draftAssessments: 8,
  inReview: 5,
  approvedAwaitingPublication: 2,
  underReviewRatings: 4,
  staleEvidenceItems: 21,
  openHighSeverityFindings: 6,
}
